sudo: required
cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
jobs:
  include:
    - stage: Test
      os: linux
      language: node_js
      node_js: 12
      install:
        - sudo apt-get install libsecret-1-dev
        - npm install -g codecov
        - npm install
      script:
        - jest --coverage
        - codecov
